name: test
on:
  pull_request:
  push:

jobs:
  test:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'
      - run: 'yarn install'
      - run: 'yarn build'
      - uses: reviewdog/action-setup@v1
      - name: 'Lint'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: '$(npm bin)/vue-cli-service lint --format checkstyle > lint.result || true && cat lint.result | reviewdog -f=checkstyle -name=vue-cli-service-lint -reporter=github-pr-review'
